"""Initial schema 2

Revision ID: 6bf71233a50f
Revises: 695d8bcc435e
Create Date: 2026-07-18 09:05:05.491841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf71233a50f'
down_revision: Union[str, Sequence[str], None] = '695d8bcc435e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('assemble_name', sa.String(length=200), nullable=False),
    sa.Column('authorize_num', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_driver_name'), 'drivers', ['driver_name'], unique=True)
    op.create_table('devices',
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('auto_start', sa.Boolean(), nullable=False),
    sa.Column('cg_upload', sa.Boolean(), nullable=False),
    sa.Column('enforce_period', sa.Integer(), nullable=False),
    sa.Column('cmd_period', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('GROUP', 'DEVICE', name='devicetypeenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=False)
    op.create_table('device_configs',
    sa.Column('device_config_name', sa.String(), nullable=False),
    sa.Column('data_side', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('enum_info', sa.String(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_variables',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('device_address', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('is_trigger', sa.Boolean(), nullable=False),
    sa.Column('endian_type', sa.String(), nullable=False),
    sa.Column('expressions', sa.String(), nullable=True),
    sa.Column('is_upload', sa.Boolean(), nullable=False),
    sa.Column('protect_type', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_variables')
    op.drop_table('device_configs')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_drivers_driver_name'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
