"""Initial migration

Revision ID: b605b98b25f4
Revises: 
Create Date: 2026-07-23 07:46:33.797119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b605b98b25f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_name', sa.String(), nullable=False, comment='Driver name'),
    sa.Column('file_name', sa.String(), nullable=False, comment='File name'),
    sa.Column('assemble_name', sa.String(), nullable=False, comment='Folder name'),
    sa.Column('authorizes_num', sa.Integer(), nullable=False, comment='Remaining number of authorizations'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('gateway_name', sa.String(), nullable=False, comment='Gateway name'),
    sa.Column('client_id', sa.String(), nullable=False, comment='ClientId'),
    sa.Column('mqtt_ip', sa.String(), nullable=False, comment='Mqtt IP'),
    sa.Column('mqtt_port', sa.Integer(), nullable=False, comment='Mqtt port'),
    sa.Column('mqtt_uname', sa.String(), nullable=False, comment='Mqtt username'),
    sa.Column('mqtt_upwd', sa.String(), nullable=False, comment='Mqtt user password'),
    sa.Column('iot_platform_type', sa.Enum('ThingsBoard', 'IoTSharp', 'AliCloudIoT', 'TencentIoTHub', 'BaiduIoTCore', 'OneNET', 'ThingsCloud', 'HuaWei', 'IoTGateway', 'ThingsPanel', name='iotplatformtype'), nullable=False, comment='Platform ouput'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='genderenum'), nullable=True),
    sa.Column('cell_phone', sa.String(), nullable=False),
    sa.Column('home_phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_name', sa.String(), nullable=False, comment='Device name'),
    sa.Column('index', sa.Integer(), nullable=False, comment='Sort'),
    sa.Column('description', sa.String(), nullable=False, comment='Description'),
    sa.Column('driver_id', sa.Uuid(), nullable=True, comment='Driver'),
    sa.Column('auto_start', sa.Boolean(), nullable=False, comment='Auto start up polling'),
    sa.Column('cg_upload', sa.Boolean(), nullable=False, comment='Changes uploaded'),
    sa.Column('enforce_period', sa.Integer(), nullable=False, comment='Polling cycle ms'),
    sa.Column('cmd_period', sa.Integer(), nullable=False, comment='Instruction interval ms'),
    sa.Column('device_type_enum', sa.Enum('Group', 'Device', name='devicetypeenum'), nullable=False, comment='Type (group or device)'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_auto_start'), 'devices', ['auto_start'], unique=False)
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_devices_device_type_enum'), 'devices', ['device_type_enum'], unique=False)
    op.create_table('device_configs',
    sa.Column('device_config_name', sa.String(), nullable=False, comment='Name'),
    sa.Column('data_side', sa.Enum('AnySide', 'ClientSide', name='dataside'), nullable=False, comment='Attribute side'),
    sa.Column('description', sa.String(), nullable=False, comment='Description'),
    sa.Column('value', sa.String(), nullable=False, comment='Value'),
    sa.Column('enum_info', sa.String(), nullable=False, comment='Remark'),
    sa.Column('device_id', sa.Uuid(), nullable=True, comment='Equipment'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_configs_device_config_name'), 'device_configs', ['device_config_name'], unique=False)
    op.create_index(op.f('ix_device_configs_value'), 'device_configs', ['value'], unique=False)
    op.create_table('device_variables',
    sa.Column('name', sa.String(), nullable=False, comment='Variable name'),
    sa.Column('description', sa.String(), nullable=False, comment='Description'),
    sa.Column('method', sa.String(), nullable=False, comment='Method'),
    sa.Column('device_address', sa.String(), nullable=False, comment='Address'),
    sa.Column('data_type', sa.Enum('Default', name='datatypeenum'), nullable=False, comment='Data types'),
    sa.Column('is_trigger', sa.Boolean(), nullable=False, comment='Trigger'),
    sa.Column('endian_type', sa.Enum('Default', name='endianenum'), nullable=False, comment='Big-endian'),
    sa.Column('expressions', sa.String(), nullable=False, comment='Expression'),
    sa.Column('is_upload', sa.Boolean(), nullable=False, comment='Upload'),
    sa.Column('protect_type', sa.Enum('Default', name='protecttypeenum'), nullable=False, comment='Permissions'),
    sa.Column('index', sa.Integer(), nullable=False, comment='Sort'),
    sa.Column('alias', sa.String(), nullable=False, comment='Alias'),
    sa.Column('device_id', sa.Uuid(), nullable=True, comment='Equipment'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_variables_data_type'), 'device_variables', ['data_type'], unique=False)
    op.create_index(op.f('ix_device_variables_device_address'), 'device_variables', ['device_address'], unique=False)
    op.create_index(op.f('ix_device_variables_method'), 'device_variables', ['method'], unique=False)
    op.create_index(op.f('ix_device_variables_name'), 'device_variables', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_variables_name'), table_name='device_variables')
    op.drop_index(op.f('ix_device_variables_method'), table_name='device_variables')
    op.drop_index(op.f('ix_device_variables_device_address'), table_name='device_variables')
    op.drop_index(op.f('ix_device_variables_data_type'), table_name='device_variables')
    op.drop_table('device_variables')
    op.drop_index(op.f('ix_device_configs_value'), table_name='device_configs')
    op.drop_index(op.f('ix_device_configs_device_config_name'), table_name='device_configs')
    op.drop_table('device_configs')
    op.drop_index(op.f('ix_devices_device_type_enum'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_auto_start'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_table('drivers')
    # ### end Alembic commands ###
