"""Add create_time, create_by, update_time, update_by fields

Revision ID: c89a7052e8ed
Revises: b605b98b25f4
Create Date: 2026-07-23 09:40:11.213717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89a7052e8ed'
down_revision: Union[str, Sequence[str], None] = 'b605b98b25f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_configs', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('device_configs', sa.Column('create_by', sa.String(length=50), nullable=True))
    op.add_column('device_configs', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('device_configs', sa.Column('update_by', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('create_by', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('update_by', sa.String(length=50), nullable=True))
    op.add_column('system_configs', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('system_configs', sa.Column('create_by', sa.String(length=50), nullable=True))
    op.add_column('system_configs', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('system_configs', sa.Column('update_by', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('create_by', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_by', sa.String(length=50), nullable=True))
    op.drop_column('users', 'home_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('users', 'update_by')
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'create_by')
    op.drop_column('users', 'create_time')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    op.drop_column('system_configs', 'update_by')
    op.drop_column('system_configs', 'update_time')
    op.drop_column('system_configs', 'create_by')
    op.drop_column('system_configs', 'create_time')
    op.drop_column('drivers', 'update_by')
    op.drop_column('drivers', 'update_time')
    op.drop_column('drivers', 'create_by')
    op.drop_column('drivers', 'create_time')
    op.drop_column('device_configs', 'update_by')
    op.drop_column('device_configs', 'update_time')
    op.drop_column('device_configs', 'create_by')
    op.drop_column('device_configs', 'create_time')
    # ### end Alembic commands ###
