apiVersion: 1

datasources:
  - name: InfluxDB-IIoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iiot-org
      defaultBucket: gateway-data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-admin-token
    isDefault: true
    editable: true
